// ─── PRODUCTS ──────────────────────────────────────────────────
const PRODUCTS = [
  { id: 1,  
   name: "Coroa Luxo Branca",   
   category: "Luxo",    
   badge: "LUXO",   
   basePrice: 395, 
   originalPrice: 450, 
   discount: 12,
   image: "imagens/coroa-luxo-branca.jpg", 
   description: "Composição luxuosa com flores brancas nobres — lírios, rosas e gérberas frescas, transmitindo paz e elegância." },

  { id: 2,  
   name: "Coroa Nobre Rosa",   
   category: "Nobre",  
   badge: "Nobre", 
   basePrice: 520, 
   originalPrice: 590,
   discount: 12,
   image: "imagens/teste.png", 
   description: "Elegante composição em tons de rosa e branco,com flores Nobre de alta durabilidade." },
  
   { id: 3,  
   name: "Coroa Luxo Mista",        
   category: "Luxo",    
   badge: "LUXO",     
   basePrice: 420, 
   originalPrice: 480,
   discount: 12,
   image: "/coroa-luxo-branca.jpg", 
   description: "Combinação harmoniosa de flores coloridas em arranjo luxuoso, ideal para homenagens especiais." },

  { id: 4,  
   name: "Coroa Nobre Amarela",      
   category: "Nobre",  
   badge: "Nobre",  
   basePrice: 480,
   originalPrice: 550, 
   discount: 13, 
   image: "/coroa-luxo-branca.jpg", 
   description: "Arranjo sofisticado com flores amarelas, transmitindo calor e luz à homenagem prestada." },

  { id: 5,  
   name: "Coroa Clássica Branca",     
   category: "Clássica", badge: "CLÁSSICA",
   basePrice: 280,
   originalPrice: 320, 
   discount: 12, 
   image: "/coroa-luxo-branca.jpg",
   description: "Tradicional e elegante, composta com flores brancas clássicas para uma homenagem simples e respeitosa." },

  { id: 6,  
   name: "Coroa Clássica Colorida",   
   category: "Clássica", 
   badge: "CLÁSSICA", 
   basePrice: 260,
   originalPrice: 300,
   discount: 13,
   image: "/coroa-luxo-branca.jpg", 
   description: "Flores coloridas em arranjo clássico, trazendo vida e cor à homenagem com bom custo-benefício." },

  { id: 7, 
  name: "Coroa Luxo Vermelha",       
  category: "Luxo",    
  badge: "LUXO",    
  basePrice: 445, 
  originalPrice: 510, 
  discount: 13, 
  image: "/coroa-luxo-branca.jpg", 
  description: "Imponente composição em vermelho intenso com rosas Nobre e folhagens exuberantes, de presença marcante." },

  { id: 8,  
  name: "Coroa Nobre Branca",       
  category: "Nobre",  
  badge: "Nobre",  
  basePrice: 580, 
  originalPrice: 660, 
  discount: 12, 
  image: "/coroa-luxo-branca.jpg", 
  description: "Majestosa coroa toda em branco com orquídeas, lírios e crisântemos selecionados, símbolo de pureza e respeito." },

  { id: 9, 
  name: "Coroa Clássica Rosa",        
  category: "Clássica", 
  badge: "CLÁSSICA", 
  basePrice: 295, 
  originalPrice: 340, 
  discount: 13, 
  image: "/coroa-luxo-branca.jpg", 
  description: "Delicada composição em tons de rosa com flores do campo, transmitindo carinho e ternura na homenagem." },

  { id: 10, 
  name: "Coroa Luxo Tropical",         
  category: "Luxo",     
  badge: "LUXO",     
  basePrice: 460, 
  originalPrice: 530, 
  discount: 13, 
  image: "/coroa-luxo-branca.jpg", 
  description: "Exuberante arranjo com flores tropicais coloridas — heliconias, antúrios e gérberas — de extrema beleza." },

  { id: 11, 
  name: "Coroa Nobre Lilás",         
  category: "Nobre",  
  badge: "Nobre",  
  basePrice: 540,
  originalPrice: 620, 
  discount: 13, 
  image: "/coroa-luxo-branca.jpg", 
  description: "Sofisticada composição em tons de lilás e roxo com flores nobres cuidadosamente selecionadas." },

  { id: 12, 
    name: "Coroa Clássica Amarela",      
    category: "Clássica", 
    badge: "CLÁSSICA", 
    basePrice: 270, 
    originalPrice: 310, 
    discount: 13, 
    image: "/coroa-luxo-branca.jpg", 
    description: "Alegre e acolhedora, com flores amarelas e brancas que trazem calor e luminosidade à cerimônia." },

  { id: 13, 
    name: "Coroa Luxo Imperial",         
    category: "Luxo",     
    badge: "LUXO",     
    basePrice: 490, 
    originalPrice: 560, 
    discount: 13,
    image: "/coroa-luxo-branca.jpg", 
    description: "Arranjo grandioso com rosas importadas, cravos e folhagens nobres. Um tributo à altura de quem se foi." },

  { id: 14, 
   name: "Coroa Nobre Pérola",        
   category: "Nobre",  
   badge: "Nobre",  
   basePrice: 620, 
   originalPrice: 710, 
   discount: 13, 
   image: "/coroa-luxo-branca.jpg", 
   description: "Exclusiva composição com flores brancas e creme em tons perlados, de elegância inigualável." },

  { id: 15, 
   name: "Coroa Clássica Mista",        
   category: "Clássica",
   badge: "CLÁSSICA", 
   basePrice: 285, 
   originalPrice: 325, 
   discount: 12, 
   image: "/coroa-luxo-branca.jpg", 
   description: "Harmoniosa mistura de flores de estação em arranjo clássico, colorido e afetuoso." },

  { id: 16,
   name: "Coroa Luxo Coral",            
   category: "Luxo",      
   badge: "LUXO",     
   basePrice: 415, 
   originalPrice: 475, 
   discount: 13, 
   image: "/coroa-luxo-branca.jpg", 
   description: "Bela composição em coral e pêssego com rosas, crisântemos e folhagens variadas de alta qualidade." },

  { id: 17, 
   name: "Coroa Nobre Champanhe",    
   category: "Nobre",  
   badge: "Nobre",  
   basePrice: 560, 
   originalPrice: 640, 
   discount: 12, 
   image: "/coroa-luxo-branca.jpg", 
   description: "Refinada composição em tons champanhe e dourado com flores nobres, transmitindo elegância única." },

  { id: 18, 
   name: "Coroa Clássica Verde",        
   category: "Clássica", 
   badge: "CLÁSSICA", 
   basePrice: 265, 
   originalPrice: 305, 
   discount: 13, 
   image: "/coroa-luxo-branca.jpg", 
   description: "Arranjo clássico com folhagens verdes naturais e flores brancas, simples e sereno." },

  { id: 19, 
   name: "Coroa Luxo Jardim",          
   category: "Luxo",     
   badge: "LUXO",    
   basePrice: 430, 
   originalPrice: 495,
   discount: 13, 
   image: "/coroa-luxo-branca.jpg", 
   description: "Evoca a beleza de um jardim florido com variedades silvestres em composição luxuosa e natural." },

  { id: 20,
   name: "Coroa Nobre Fucsia",       
   category: "Nobre", 
   badge: "Nobre",  
   basePrice: 510, 
   originalPrice: 585,
   discount: 13, 
   image: "/coroa-luxo-branca.jpg", description: "Vibrante e marcante composição em fucsia e magenta com flores Nobre de alto impacto visual." },

  { id: 21, 
   name: "Coroa Clássica Lilás",       
   category: "Clássica", 
   badge: "CLÁSSICA",
   basePrice: 275,
   originalPrice: 315, 
   discount: 13, 
   image: "/coroa-luxo-branca.jpg", 
   description: "Suave composição em lilás e lavanda com flores do campo, delicada e singela." },

  { id: 22,
   name: "Coroa Luxo Natureza",        
   category: "Luxo",    
   badge: "LUXO",    
   basePrice: 450, 
   originalPrice: 515,
   discount: 13, 
   image: "/coroa-luxo-branca.jpg", 
   description: "Inspirada na natureza, com folhagens nobres, flores silvestres e arranjo orgânico de extrema sofisticação." },

  { id: 23, 
   name: "Coroa Nobre Exclusiva",    
   category: "Nobre", 
   badge: "Nobre",  
   basePrice: 680, 
   originalPrice: 780, 
   discount: 13, 
   image: "/coroa-luxo-branca.jpg", 
   description: "Nossa linha mais requintada, com flores importadas e arranjo personalizado. A homenagem mais especial possível." },

  { id: 24, 
   name: "Coroa Clássica Simples",     
   category: "Clássica",
   badge: "CLÁSSICA", 
   basePrice: 240, 
   originalPrice: 275, 
   discount: 13, 
   image: "/coroa-luxo-branca.jpg", 
   description: "Opção econômica sem abrir mão da qualidade e do respeito. Flores frescas em arranjo singelo e digno." },

  { id: 25,
   name: "Coroa Luxo Borboleta",       
   category: "Luxo",    
   badge: "LUXO",     
   basePrice: 435, 
   originalPrice: 500,
   discount: 13,
   image: "/coroa-luxo-branca.jpg",
   description: "Arranjo delicado e leve como borboletas, com flores suaves e translúcidas em tons pastéis luxuosos." },
];

// ─── SIZES ─────────────────────────────────────────────────────
const SIZES = [
  { id: "P", label: "Pequena", dimensions: "1,00m × 1,00m", addon: 0 },
  { id: "M", label: "Média", dimensions: "1,00m × 1,20m", addon: 50 },
  { id: "G", label: "Grande", dimensions: "1,00m × 1,50m", addon: 100 },
];

// ─── CEMETERIES ────────────────────────────────────────────────
const CEMETERIES = [
  { id: 1, 
    name: "Cemitério da Consolação", 
    address: "R. da Consolação, 1600", 
    city: "São Paulo", 
    state: "SP", 
    phone: "(11) 3256-9081", 
    hours: "Seg–Dom: 7h–17h", 
    mapQuery: "Cemitério da Consolação, São Paulo, SP" },

  { id: 2,
     name: "Cemitério do Araçá", 
     address: "Av. Dr. Arnaldo, 671", 
     city: "São Paulo", 
     state: "SP", 
     phone: "(11) 3872-0677", 
     hours: "Seg–Dom: 7h–17h", 
     mapQuery: "Cemitério do Araçá, São Paulo, SP" },

  { id: 3, 
    name: "Cemitério do Morumbi", 
    address: "R. Dep. Laércio Corte, 700", 
    city: "São Paulo", 
    state: "SP",
    phone: "(11) 3742-2222", 
    hours: "Seg–Dom: 6h–18h", 
    mapQuery: "Cemitério do Morumbi, São Paulo, SP" },

  { id: 4, 
    name: "Cemitério Vila Formosa", 
    address: "Av. Afonso de Freitas, 1400",
    city: "São Paulo", 
    state: "SP", 
    phone: "(11) 6945-5299", 
    hours: "Seg–Dom: 7h–17h",
    mapQuery: "Cemitério Vila Formosa, São Paulo, SP" },

  { id: 5, 
    name: "Cemitério Gethsemani", 
    address: "Av. Indianápolis, 1020", 
    city: "São Paulo", 
    state: "SP",
    phone: "(11) 5071-5455", 
    hours: "Seg–Dom: 7h–18h", 
    mapQuery: "Cemitério Gethsemani, São Paulo, SP" },

  { id: 6, 
    name: "Cemitério Nossa Sra. Aparecida", 
    address: "R. Nossa Sra. Aparecida, 500", 
    city: "São Paulo", 
    state: "SP", 
    phone: "(11) 3333-4444",
    hours: "Seg–Dom: 7h–17h", 
    mapQuery: "Cemitério Nossa Senhora Aparecida, São Paulo, SP" },

  { id: 7, 
    name: "Cemitério São Paulo", 
    address: "R. do Lavapés, 720", 
    city: "São Paulo", 
    state: "SP", 
    phone: "(11) 3209-4888", 
    hours: "Seg–Dom: 7h–17h", 
    mapQuery: "Cemitério São Paulo, Glicério, SP" },

  { id: 8, 
    name: "Cemitério Cristo Redentor",
    address: "Av. Cangaíba, 400", 
    city: "São Paulo", 
    state: "SP",
    phone: "(11) 2954-1122", 
    hours: "Seg–Dom: 7h–17h",
    mapQuery: "Cemitério Cristo Redentor, São Paulo, SP" },

  { id: 9, 
    name: "Cemitério Quarta Parada", 
    address: "R. Bresser, 3005", 
    city: "São Paulo", 
    state: "SP",
    phone: "(11) 6693-4060", 
    hours: "Seg–Dom: 7h–17h", 
    mapQuery: "Cemitério Quarta Parada, São Paulo, SP" },


  { id: 10, 
    name: "Cemitério Jardim da Colina", 
    address: "Av. Moraes Barros, 1800", 
    city: "Campinas", 
    state: "SP", 
    phone: "(19) 3773-3773", 
    hours: "Seg–Dom: 7h–18h", 
    mapQuery: "Cemitério Jardim da Colina, Campinas, SP" },

  { id: 11, 
    name: "Cemitério Parque das Flores", 
    address: "Estrada do Campo Limpo, 2000", 
    city: "São Paulo", 
    state: "SP", 
    phone: "(11) 5822-3000", 
    hours: "Seg–Dom: 8h–18h", 
    mapQuery: "Cemitério Parque das Flores, São Paulo, SP" },

  { id: 12, 
    name: "Cemitério Parque Independência", 
    address: "Av. João Dias, 2080", 
    city: "São Paulo", 
    state: "SP", 
    phone: "(11) 5677-1414", 
    hours: "Seg–Dom: 7h–17h",
    mapQuery: "Cemitério Parque Independência, Santo André, SP" },
];

// ─── PHRASES ───────────────────────────────────────────────────
const PHRASE_CATS = ["Religiosas", "Para a Família", "Amigos", "Profissional", "Poéticas"];

const PHRASES = [
  { id: 1, cat: "Religiosas", text: "O Senhor é o meu pastor, e nada me faltará. Que Deus console seu coração neste momento de dor." },
  { id: 2, cat: "Religiosas", text: "Partiu para os braços do Pai. Com nossas orações e carinho eternos." },
  { id: 3, cat: "Religiosas", text: "Que Deus, em sua infinita misericórdia, acolha esta alma e conforte os corações que ficaram." },
  { id: 4, cat: "Religiosas", text: "Foi para o lugar onde não há mais dor. Que a paz de Deus esteja com sua família." },
  { id: 5, cat: "Religiosas", text: "Descanse nos braços do Senhor. Nossa fé nos dá a certeza do reencontro." },
  { id: 6, cat: "Religiosas", text: "A vida é uma passagem. A eternidade é o destino. Com amor e fé." },
  { id: 7, cat: "Religiosas", text: "Que Nossa Senhora interceda por esta alma e traga conforto à família enlutada." },

  { id: 8, cat: "Para a Família", text: "Da família, com muito amor e eterna saudade." },
  { id: 9, cat: "Para a Família", text: "Seu amor e carinho viverão para sempre em nossos corações. Com saudade eterna." },
  { id: 10, cat: "Para a Família", text: "Papai/Mamãe, você partiu, mas jamais será esquecido(a). Com todo o nosso amor." },
  { id: 11, cat: "Para a Família", text: "Uma vida dedicada à família. Uma lembrança que jamais se apagará. Com saudade, seus filhos." },
  { id: 12, cat: "Para a Família", text: "Avô/Avó querido(a), seu legado de amor e sabedoria viverá em nós para sempre." },
  { id: 13, cat: "Para a Família", text: "Com profunda saudade e amor eterno, de seus filhos e netos." },
  { id: 14, cat: "Para a Família", text: "Você nos ensinou o que é o amor. Essa lição ficará para sempre. Da sua família." },

  { id: 15, cat: "Amigos", text: "Um amigo que partiu, mas cuja amizade ficará eternamente em nossos corações." },
  { id: 16, cat: "Amigos", text: "Obrigado por cada momento compartilhado. Sua partida deixa uma saudade sem tamanho." },
  { id: 17, cat: "Amigos", text: "Amigos para sempre, em vida e em memória. Com carinho e saudade." },
  { id: 18, cat: "Amigos", text: "Que descanse em paz. Você marcou a vida de todos que te conheceram." },
  { id: 19, cat: "Amigos", text: "Da turma do coração, com amizade eterna e muita saudade." },
  { id: 20, cat: "Amigos", text: "Você foi muito mais que um amigo. Foi parte da nossa família. Saudades." },

  { id: 21, cat: "Profissional", text: "Em nome de todos os colegas, expressamos nossa mais profunda solidariedade e saudade." },
  { id: 22, cat: "Profissional", text: "Um profissional exemplar, que deixou sua marca em tudo que fez. Sentiremos sua falta." },
  { id: 23, cat: "Profissional", text: "Seus colegas de trabalho, com respeito e admiração, prestam esta última homenagem." },
  { id: 24, cat: "Profissional", text: "A empresa e seus colaboradores lamentam profundamente a perda e se solidarizam com a família." },
  { id: 25, cat: "Profissional", text: "Seu talento e dedicação foram inspiração para todos nós. Com saudade e gratidão." },

  { id: 26, cat: "Poéticas", text: "\"Não chores por minha partida, sorria por termos nos encontrado.\" Com amor eterno." },
  { id: 27, cat: "Poéticas", text: "As flores murcham, mas a saudade floresce para sempre em nossos corações." },
  { id: 28, cat: "Poéticas", text: "Quem deixa amor jamais parte de verdade. Vive em cada lembrança, em cada sorriso." },
  { id: 29, cat: "Poéticas", text: "A morte separa corpos, mas nunca almas. Você viverá em nós enquanto existirmos." },
  { id: 30, cat: "Poéticas", text: "Uma estrela a mais brilha no céu esta noite. Com amor e saudade infinita." },
  { id: 31, cat: "Poéticas", text: "Não é adeus, é até logo. A saudade é o preço do amor que sentimos." },
  { id: 32, cat: "Poéticas", text: "Que a leveza das flores represente a paz que você tanto merecia. Com carinho eterno." },
];

const WHATSAPP = "551142126660";
const PHONE = "(11) 42126660";

function fmtPrice(n) { return "R$ " + n.toFixed(2).replace(".", ","); }
function fmtDate(d) { if (!d) return ""; const [y,m,day] = d.split("-"); return `${day}/${m}/${y}`; }
